# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7570432e74d02a87aafd04391985c69a"
name = "shoptempl-rails-react"
handle = "shoptempl-rails-react"
application_url = "https://levitra-yards-hon-hl.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "tyghs-test-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://levitra-yards-hon-hl.trycloudflare.com/auth/callback",
  "https://levitra-yards-hon-hl.trycloudflare.com/auth/shopify/callback",
  "https://levitra-yards-hon-hl.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/customers_data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/customers_redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/shop_redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/api/webhooks/app_uninstalled"

[pos]
embedded = false
